<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Lga;

class LgaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $lgas = array(
        array('id' => '6','state_id' => '2','name' => 'ABA NORTH'),
        array('id' => '7','state_id' => '2','name' => 'ABA SOUTH'),
        array('id' => '8','state_id' => '2','name' => 'AROCHUKWU'),
        array('id' => '9','state_id' => '2','name' => 'BENDE'),
        array('id' => '10','state_id' => '2','name' => 'IKWUANO'),
        array('id' => '11','state_id' => '2','name' => 'ISIALA NGWA NORTH'),
        array('id' => '12','state_id' => '2','name' => 'ISIALA NGWA SOUTH'),
        array('id' => '13','state_id' => '2','name' => 'ISUIKWUATO'),
        array('id' => '14','state_id' => '2','name' => 'OBI NGWA'),
        array('id' => '15','state_id' => '2','name' => 'OHAFIA'),
        array('id' => '16','state_id' => '2','name' => 'OSISIOMA'),
        array('id' => '17','state_id' => '2','name' => 'UGWUNAGBO'),
        array('id' => '18','state_id' => '2','name' => 'UKWA EAST'),
        array('id' => '19','state_id' => '2','name' => 'UKWA WEST'),
        array('id' => '20','state_id' => '2','name' => 'UMUAHIA NORTH'),
        array('id' => '21','state_id' => '2','name' => 'UMUAHIA SOUTH'),
        array('id' => '22','state_id' => '2','name' => 'UMU NNEOCHI'),
        array('id' => '23','state_id' => '2','name' => 'OBI NGWA'),
        array('id' => '24','state_id' => '3','name' => 'DEMSA'),
        array('id' => '25','state_id' => '3','name' => 'FUFURE'),
        array('id' => '26','state_id' => '3','name' => 'GANYE'),
        array('id' => '27','state_id' => '3','name' => 'GAYUK'),
        array('id' => '28','state_id' => '3','name' => 'GOMBI'),
        array('id' => '29','state_id' => '3','name' => 'GRIE'),
        array('id' => '30','state_id' => '3','name' => 'HONG'),
        array('id' => '31','state_id' => '3','name' => 'JADA'),
        array('id' => '32','state_id' => '3','name' => 'LAMURDE'),
        array('id' => '33','state_id' => '3','name' => 'MADAGALI'),
        array('id' => '34','state_id' => '3','name' => 'MAIHA'),
        array('id' => '35','state_id' => '3','name' => 'MAYO BELWA'),
        array('id' => '36','state_id' => '3','name' => 'MICHIKA'),
        array('id' => '37','state_id' => '3','name' => 'MUBI NORTH'),
        array('id' => '38','state_id' => '3','name' => 'MUBI SOUTH'),
        array('id' => '39','state_id' => '3','name' => 'NUMAN'),
        array('id' => '40','state_id' => '3','name' => 'SHELLENG'),
        array('id' => '41','state_id' => '3','name' => 'SONG'),
        array('id' => '42','state_id' => '3','name' => 'TOUNGO'),
        array('id' => '43','state_id' => '3','name' => 'YOLA NORTH'),
        array('id' => '44','state_id' => '3','name' => 'YOLA SOUTH'),
        array('id' => '45','state_id' => '5','name' => 'ABAK'),
        array('id' => '46','state_id' => '5','name' => 'EASTERN OBOLO'),
        array('id' => '47','state_id' => '5','name' => 'EKET'),
        array('id' => '48','state_id' => '5','name' => 'ESIT EKET'),
        array('id' => '49','state_id' => '5','name' => 'ESSIEN UDIM'),
        array('id' => '50','state_id' => '5','name' => 'ETIM EKPO'),
        array('id' => '51','state_id' => '5','name' => 'ETINAN'),
        array('id' => '52','state_id' => '5','name' => 'IBENO'),
        array('id' => '53','state_id' => '5','name' => 'IBESIKPO ASUTAN'),
        array('id' => '54','state_id' => '5','name' => 'IBIONO-IBOM'),
        array('id' => '55','state_id' => '5','name' => 'IKA'),
        array('id' => '56','state_id' => '5','name' => 'IKONO'),
        array('id' => '57','state_id' => '5','name' => 'IKOT ABASI'),
        array('id' => '58','state_id' => '5','name' => 'IKOT EKPENE'),
        array('id' => '59','state_id' => '5','name' => 'INI'),
        array('id' => '60','state_id' => '5','name' => 'ITU'),
        array('id' => '61','state_id' => '5','name' => 'MBO'),
        array('id' => '62','state_id' => '5','name' => 'MKPAT-ENIN'),
        array('id' => '63','state_id' => '5','name' => 'NSIT-ATAI'),
        array('id' => '64','state_id' => '5','name' => 'NSIT-IBOM'),
        array('id' => '65','state_id' => '5','name' => 'NSIT-UBIUM'),
        array('id' => '66','state_id' => '5','name' => 'OBOT AKARA'),
        array('id' => '67','state_id' => '5','name' => 'OKOBO'),
        array('id' => '68','state_id' => '5','name' => 'ONNA'),
        array('id' => '69','state_id' => '5','name' => 'ORON'),
        array('id' => '70','state_id' => '5','name' => 'ORUK ANAM'),
        array('id' => '71','state_id' => '5','name' => 'UDUNG-UKO'),
        array('id' => '72','state_id' => '5','name' => 'UKANAFUN'),
        array('id' => '73','state_id' => '5','name' => 'URUAN'),
        array('id' => '74','state_id' => '5','name' => 'URUE-OFFONG/ORUKO'),
        array('id' => '75','state_id' => '5','name' => 'UYO'),
        array('id' => '76','state_id' => '5','name' => 'OBOT AKARA'),
        array('id' => '77','state_id' => '4','name' => 'AGUATA'),
        array('id' => '78','state_id' => '4','name' => 'ANAMBRA EAST'),
        array('id' => '79','state_id' => '4','name' => 'ANAMBRA WEST'),
        array('id' => '80','state_id' => '4','name' => 'ANAOCHA'),
        array('id' => '81','state_id' => '4','name' => 'AWKA NORTH'),
        array('id' => '82','state_id' => '4','name' => 'AWKA SOUTH'),
        array('id' => '83','state_id' => '4','name' => 'AYAMELUM'),
        array('id' => '84','state_id' => '4','name' => 'DUNUKOFIA'),
        array('id' => '85','state_id' => '4','name' => 'EKWUSIGO'),
        array('id' => '86','state_id' => '4','name' => 'IDEMILI NORTH'),
        array('id' => '87','state_id' => '4','name' => 'IDEMILI SOUTH'),
        array('id' => '88','state_id' => '4','name' => 'IHIALA'),
        array('id' => '89','state_id' => '4','name' => 'NJIKOKA'),
        array('id' => '90','state_id' => '4','name' => 'NNEWI NORTH'),
        array('id' => '91','state_id' => '4','name' => 'NNEWI SOUTH'),
        array('id' => '92','state_id' => '4','name' => 'OGBARU'),
        array('id' => '93','state_id' => '4','name' => 'ONITSHA NORTH'),
        array('id' => '94','state_id' => '4','name' => 'ONITSHA SOUTH'),
        array('id' => '95','state_id' => '4','name' => 'ORUMBA NORTH'),
        array('id' => '96','state_id' => '4','name' => 'ORUMBA SOUTH'),
        array('id' => '97','state_id' => '4','name' => 'OYI'),
        array('id' => '98','state_id' => '6','name' => 'ALKALERI'),
        array('id' => '99','state_id' => '6','name' => 'BAUCHI'),
        array('id' => '100','state_id' => '6','name' => 'BOGORO'),
        array('id' => '101','state_id' => '6','name' => 'DAMBAN'),
        array('id' => '102','state_id' => '6','name' => 'DARAZO'),
        array('id' => '103','state_id' => '6','name' => 'DASS'),
        array('id' => '104','state_id' => '6','name' => 'GAMAWA'),
        array('id' => '105','state_id' => '6','name' => 'GANJUWA'),
        array('id' => '106','state_id' => '6','name' => 'GIADE'),
        array('id' => '107','state_id' => '6','name' => 'ITAS/GADAU'),
        array('id' => '108','state_id' => '6','name' => 'JAMA\'ARE'),
        array('id' => '109','state_id' => '6','name' => 'KATAGUM'),
        array('id' => '110','state_id' => '6','name' => 'KIRFI'),
        array('id' => '111','state_id' => '6','name' => 'MISAU'),
        array('id' => '112','state_id' => '6','name' => 'NINGI'),
        array('id' => '113','state_id' => '6','name' => 'SHIRA'),
        array('id' => '114','state_id' => '6','name' => 'TAFAWA BALEWA'),
        array('id' => '115','state_id' => '6','name' => 'TORO'),
        array('id' => '116','state_id' => '6','name' => 'WARJI'),
        array('id' => '117','state_id' => '6','name' => 'ZAKI'),
        array('id' => '118','state_id' => '7','name' => 'BRASS'),
        array('id' => '119','state_id' => '7','name' => 'EKEREMOR'),
        array('id' => '120','state_id' => '7','name' => 'KOLOKUMA/OPOKUMA'),
        array('id' => '121','state_id' => '7','name' => 'NEMBE'),
        array('id' => '122','state_id' => '7','name' => 'OGBIA'),
        array('id' => '123','state_id' => '7','name' => 'SAGBAMA'),
        array('id' => '124','state_id' => '7','name' => 'SOUTHERN IJAW'),
        array('id' => '125','state_id' => '7','name' => 'YENAGOA'),
        array('id' => '126','state_id' => '8','name' => 'AGATU'),
        array('id' => '127','state_id' => '8','name' => 'APA'),
        array('id' => '128','state_id' => '8','name' => 'ADO'),
        array('id' => '129','state_id' => '8','name' => 'BURUKU'),
        array('id' => '130','state_id' => '8','name' => 'GBOKO'),
        array('id' => '131','state_id' => '8','name' => 'GUMA'),
        array('id' => '132','state_id' => '8','name' => 'GWER EAST'),
        array('id' => '133','state_id' => '8','name' => 'GWER WEST'),
        array('id' => '134','state_id' => '8','name' => 'KATSINA-ALA'),
        array('id' => '135','state_id' => '8','name' => 'KONSHISHA'),
        array('id' => '136','state_id' => '8','name' => 'KWANDE'),
        array('id' => '137','state_id' => '8','name' => 'LOGO'),
        array('id' => '138','state_id' => '8','name' => 'MAKURDI'),
        array('id' => '139','state_id' => '8','name' => 'OBI'),
        array('id' => '140','state_id' => '8','name' => 'OGBADIBO'),
        array('id' => '141','state_id' => '8','name' => 'OHIMINI'),
        array('id' => '142','state_id' => '8','name' => 'OJU'),
        array('id' => '143','state_id' => '8','name' => 'OKPOKWU'),
        array('id' => '144','state_id' => '8','name' => 'OTURKPO'),
        array('id' => '145','state_id' => '8','name' => 'TARKA'),
        array('id' => '146','state_id' => '8','name' => 'UKUM'),
        array('id' => '147','state_id' => '8','name' => 'USHONGO'),
        array('id' => '148','state_id' => '8','name' => 'VANDEIKYA'),
        array('id' => '149','state_id' => '8','name' => 'OBI'),
        array('id' => '150','state_id' => '9','name' => 'ABADAM'),
        array('id' => '151','state_id' => '9','name' => 'ASKIRA/UBA'),
        array('id' => '152','state_id' => '9','name' => 'BAMA'),
        array('id' => '153','state_id' => '9','name' => 'BAYO'),
        array('id' => '154','state_id' => '9','name' => 'BIU'),
        array('id' => '155','state_id' => '9','name' => 'CHIBOK'),
        array('id' => '156','state_id' => '9','name' => 'DAMBOA'),
        array('id' => '157','state_id' => '9','name' => 'DIKWA'),
        array('id' => '158','state_id' => '9','name' => 'GUBIO'),
        array('id' => '159','state_id' => '9','name' => 'GUZAMALA'),
        array('id' => '160','state_id' => '9','name' => 'GWOZA'),
        array('id' => '161','state_id' => '9','name' => 'HAWUL'),
        array('id' => '162','state_id' => '9','name' => 'JERE'),
        array('id' => '163','state_id' => '9','name' => 'KAGA'),
        array('id' => '164','state_id' => '9','name' => 'KALA/BALGE'),
        array('id' => '165','state_id' => '9','name' => 'KONDUGA'),
        array('id' => '166','state_id' => '9','name' => 'KUKAWA'),
        array('id' => '167','state_id' => '9','name' => 'KWAYA KUSAR'),
        array('id' => '168','state_id' => '9','name' => 'MAFA'),
        array('id' => '169','state_id' => '9','name' => 'MAGUMERI'),
        array('id' => '170','state_id' => '9','name' => 'MAIDUGURI'),
        array('id' => '171','state_id' => '9','name' => 'MARTE'),
        array('id' => '172','state_id' => '9','name' => 'MOBBAR'),
        array('id' => '173','state_id' => '9','name' => 'MONGUNO'),
        array('id' => '174','state_id' => '9','name' => 'NGALA'),
        array('id' => '175','state_id' => '9','name' => 'NGANZAI'),
        array('id' => '176','state_id' => '9','name' => 'SHANI'),
        array('id' => '177','state_id' => '10','name' => 'ABI'),
        array('id' => '178','state_id' => '10','name' => 'AKAMKPA'),
        array('id' => '179','state_id' => '10','name' => 'AKPABUYO'),
        array('id' => '180','state_id' => '10','name' => 'BAKASSI'),
        array('id' => '181','state_id' => '10','name' => 'BEKWARRA'),
        array('id' => '182','state_id' => '10','name' => 'BIASE'),
        array('id' => '183','state_id' => '10','name' => 'BOKI'),
        array('id' => '184','state_id' => '10','name' => 'CALABAR MUNICIPAL'),
        array('id' => '185','state_id' => '10','name' => 'CALABAR SOUTH'),
        array('id' => '186','state_id' => '10','name' => 'ETUNG'),
        array('id' => '187','state_id' => '10','name' => 'IKOM'),
        array('id' => '188','state_id' => '10','name' => 'OBANLIKU'),
        array('id' => '189','state_id' => '10','name' => 'OBUBRA'),
        array('id' => '190','state_id' => '10','name' => 'OBUDU'),
        array('id' => '191','state_id' => '10','name' => 'ODUKPANI'),
        array('id' => '192','state_id' => '10','name' => 'OGOJA'),
        array('id' => '193','state_id' => '10','name' => 'YAKUUR'),
        array('id' => '194','state_id' => '10','name' => 'OBUBRA'),
        array('id' => '195','state_id' => '10','name' => 'YALA'),
        array('id' => '196','state_id' => '11','name' => 'ANIOCHA NORTH'),
        array('id' => '197','state_id' => '11','name' => 'ANIOCHA SOUTH'),
        array('id' => '198','state_id' => '11','name' => 'BOMADI'),
        array('id' => '199','state_id' => '11','name' => 'BURUTU'),
        array('id' => '200','state_id' => '11','name' => 'ETHIOPE EAST'),
        array('id' => '201','state_id' => '11','name' => 'ETHIOPE WEST'),
        array('id' => '202','state_id' => '11','name' => 'IKA NORTH EAST'),
        array('id' => '203','state_id' => '11','name' => 'IKA SOUTH'),
        array('id' => '204','state_id' => '11','name' => 'ISOKO NORTH'),
        array('id' => '205','state_id' => '11','name' => 'ISOKO SOUTH'),
        array('id' => '206','state_id' => '11','name' => 'NDOKWA EAST'),
        array('id' => '207','state_id' => '11','name' => 'NDOKWA WEST'),
        array('id' => '208','state_id' => '11','name' => 'OKPE'),
        array('id' => '209','state_id' => '11','name' => 'OSHIMILI NORTH'),
        array('id' => '210','state_id' => '11','name' => 'OSHIMILI SOUTH'),
        array('id' => '211','state_id' => '11','name' => 'PATANI'),
        array('id' => '212','state_id' => '11','name' => 'SAPELE'),
        array('id' => '213','state_id' => '11','name' => 'UDU'),
        array('id' => '214','state_id' => '11','name' => 'UGHELLI NORTH'),
        array('id' => '215','state_id' => '11','name' => 'UGHELLI SOUTH'),
        array('id' => '216','state_id' => '11','name' => 'UKWUANI'),
        array('id' => '217','state_id' => '11','name' => 'UVWIE'),
        array('id' => '218','state_id' => '11','name' => 'WARRI NORTH'),
        array('id' => '219','state_id' => '11','name' => 'WARRI SOUTH'),
        array('id' => '220','state_id' => '11','name' => 'WARRI SOUTH WEST'),
        array('id' => '221','state_id' => '12','name' => 'ABAKALIKI'),
        array('id' => '222','state_id' => '12','name' => 'AFIKPO NORTH'),
        array('id' => '223','state_id' => '12','name' => 'AFIKPO SOUTH (EDDA)'),
        array('id' => '224','state_id' => '12','name' => 'EBONYI'),
        array('id' => '225','state_id' => '12','name' => 'EZZA NORTH'),
        array('id' => '226','state_id' => '12','name' => 'EZZA SOUTH'),
        array('id' => '227','state_id' => '12','name' => 'IKWO'),
        array('id' => '228','state_id' => '12','name' => 'ISHIELU'),
        array('id' => '229','state_id' => '12','name' => 'IVO'),
        array('id' => '230','state_id' => '12','name' => 'IZZI'),
        array('id' => '231','state_id' => '12','name' => 'OHAOZARA'),
        array('id' => '232','state_id' => '12','name' => 'OHAUKWU'),
        array('id' => '233','state_id' => '12','name' => 'ONICHA'),
        array('id' => '234','state_id' => '14','name' => 'AKOKO-EDO'),
        array('id' => '235','state_id' => '14','name' => 'EGOR'),
        array('id' => '236','state_id' => '14','name' => 'ESAN CENTRAL'),
        array('id' => '237','state_id' => '14','name' => 'ESAN NORTH-EAST'),
        array('id' => '238','state_id' => '14','name' => 'ESAN SOUTH-EAST'),
        array('id' => '239','state_id' => '14','name' => 'ESAN WEST'),
        array('id' => '240','state_id' => '14','name' => 'ETSAKO CENTRAL'),
        array('id' => '241','state_id' => '14','name' => 'ETSAKO EAST'),
        array('id' => '242','state_id' => '14','name' => 'ETSAKO WEST'),
        array('id' => '243','state_id' => '14','name' => 'IGUEBEN'),
        array('id' => '244','state_id' => '14','name' => 'IKPOBA OKHA'),
        array('id' => '245','state_id' => '14','name' => 'ORHIONMWON'),
        array('id' => '246','state_id' => '14','name' => 'OREDO'),
        array('id' => '247','state_id' => '14','name' => 'OVIA NORTH-EAST'),
        array('id' => '248','state_id' => '14','name' => 'OVIA SOUTH-WEST'),
        array('id' => '249','state_id' => '14','name' => 'OWAN EAST'),
        array('id' => '250','state_id' => '14','name' => 'OWAN WEST'),
        array('id' => '251','state_id' => '14','name' => 'UHUNMWONDE'),
        array('id' => '252','state_id' => '15','name' => 'ADO EKITI'),
        array('id' => '253','state_id' => '15','name' => 'EFON'),
        array('id' => '254','state_id' => '15','name' => 'EKITI EAST'),
        array('id' => '255','state_id' => '15','name' => 'EKITI SOUTH-WEST'),
        array('id' => '256','state_id' => '15','name' => 'EKITI WEST'),
        array('id' => '257','state_id' => '15','name' => 'EMURE'),
        array('id' => '258','state_id' => '15','name' => 'GBONYIN'),
        array('id' => '259','state_id' => '15','name' => 'IDO OSI'),
        array('id' => '260','state_id' => '15','name' => 'IJERO'),
        array('id' => '261','state_id' => '15','name' => 'IKERE'),
        array('id' => '262','state_id' => '15','name' => 'IKOLE'),
        array('id' => '263','state_id' => '15','name' => 'ILEJEMEJE'),
        array('id' => '264','state_id' => '15','name' => 'IREPODUN/IFELODUN'),
        array('id' => '265','state_id' => '15','name' => 'ISE/ORUN'),
        array('id' => '266','state_id' => '15','name' => 'MOBA'),
        array('id' => '267','state_id' => '15','name' => 'OYE'),
        array('id' => '268','state_id' => '13','name' => 'ANINRI'),
        array('id' => '269','state_id' => '13','name' => 'AWGU'),
        array('id' => '270','state_id' => '13','name' => 'ENUGU EAST'),
        array('id' => '271','state_id' => '13','name' => 'ENUGU NORTH'),
        array('id' => '272','state_id' => '13','name' => 'ENUGU SOUTH'),
        array('id' => '273','state_id' => '13','name' => 'EZEAGU'),
        array('id' => '274','state_id' => '13','name' => 'IGBO ETITI'),
        array('id' => '275','state_id' => '13','name' => 'IGBO EZE NORTH'),
        array('id' => '276','state_id' => '13','name' => 'IGBO EZE SOUTH'),
        array('id' => '277','state_id' => '13','name' => 'ISI UZO'),
        array('id' => '278','state_id' => '13','name' => 'NKANU EAST'),
        array('id' => '279','state_id' => '13','name' => 'NKANU WEST'),
        array('id' => '280','state_id' => '13','name' => 'NSUKKA'),
        array('id' => '281','state_id' => '13','name' => 'OJI RIVER'),
        array('id' => '282','state_id' => '13','name' => 'UDENU'),
        array('id' => '283','state_id' => '13','name' => 'UDI'),
        array('id' => '284','state_id' => '13','name' => 'UZO-UWANI'),
        array('id' => '285','state_id' => '38','name' => 'ABAJI'),
        array('id' => '286','state_id' => '38','name' => 'ABUJA'),
        array('id' => '287','state_id' => '38','name' => 'BWARI'),
        array('id' => '288','state_id' => '38','name' => 'GWAGWALADA'),
        array('id' => '289','state_id' => '38','name' => 'KUJE'),
        array('id' => '290','state_id' => '38','name' => 'KWALI'),
        array('id' => '291','state_id' => '16','name' => 'AKKO'),
        array('id' => '292','state_id' => '16','name' => 'BALANGA'),
        array('id' => '293','state_id' => '16','name' => 'BILLIRI'),
        array('id' => '294','state_id' => '16','name' => 'DUKKU'),
        array('id' => '295','state_id' => '16','name' => 'FUNAKAYE'),
        array('id' => '296','state_id' => '16','name' => 'GOMBE'),
        array('id' => '297','state_id' => '16','name' => 'KALTUNGO'),
        array('id' => '298','state_id' => '16','name' => 'KWAMI'),
        array('id' => '299','state_id' => '16','name' => 'NAFADA'),
        array('id' => '300','state_id' => '16','name' => 'SHONGOM'),
        array('id' => '301','state_id' => '16','name' => 'YAMALTU/DEBA'),
        array('id' => '302','state_id' => '17','name' => 'ABOH MBAISE'),
        array('id' => '303','state_id' => '17','name' => 'AHIAZU MBAISE'),
        array('id' => '304','state_id' => '17','name' => 'EHIME MBANO'),
        array('id' => '305','state_id' => '17','name' => 'EZINIHITTE'),
        array('id' => '306','state_id' => '17','name' => 'IDEATO NORTH'),
        array('id' => '307','state_id' => '17','name' => 'IDEATO SOUTH'),
        array('id' => '308','state_id' => '17','name' => 'IHITTE/UBOMA'),
        array('id' => '309','state_id' => '17','name' => 'IKEDURU'),
        array('id' => '310','state_id' => '17','name' => 'ISIALA MBANO'),
        array('id' => '311','state_id' => '17','name' => 'ISU'),
        array('id' => '312','state_id' => '17','name' => 'MBAITOLI'),
        array('id' => '313','state_id' => '17','name' => 'NGOR OKPALA'),
        array('id' => '314','state_id' => '17','name' => 'NJABA'),
        array('id' => '315','state_id' => '17','name' => 'NKWERRE'),
        array('id' => '316','state_id' => '17','name' => 'NWANGELE'),
        array('id' => '317','state_id' => '17','name' => 'OBOWO'),
        array('id' => '318','state_id' => '17','name' => 'OGUTA'),
        array('id' => '319','state_id' => '17','name' => 'OHAJI/EGBEMA'),
        array('id' => '320','state_id' => '17','name' => 'OKIGWE'),
        array('id' => '321','state_id' => '17','name' => 'ORLU'),
        array('id' => '322','state_id' => '17','name' => 'ORSU'),
        array('id' => '323','state_id' => '17','name' => 'ORU EAST'),
        array('id' => '324','state_id' => '17','name' => 'ORU WEST'),
        array('id' => '325','state_id' => '17','name' => 'OWERRI MUNICIPAL'),
        array('id' => '326','state_id' => '17','name' => 'OWERRI NORTH'),
        array('id' => '327','state_id' => '17','name' => 'OWERRI WEST'),
        array('id' => '328','state_id' => '17','name' => 'UNUIMO'),
        array('id' => '329','state_id' => '17','name' => 'OBOWO'),
        array('id' => '330','state_id' => '18','name' => 'AUYO'),
        array('id' => '331','state_id' => '18','name' => 'BABURA'),
        array('id' => '332','state_id' => '18','name' => 'BIRINIWA'),
        array('id' => '333','state_id' => '18','name' => 'BIRNIN KUDU'),
        array('id' => '334','state_id' => '18','name' => 'BUJI'),
        array('id' => '335','state_id' => '18','name' => 'DUTSE'),
        array('id' => '336','state_id' => '18','name' => 'GAGARAWA'),
        array('id' => '337','state_id' => '18','name' => 'GARKI'),
        array('id' => '338','state_id' => '18','name' => 'GUMEL'),
        array('id' => '339','state_id' => '18','name' => 'GURI'),
        array('id' => '340','state_id' => '18','name' => 'GWARAM'),
        array('id' => '341','state_id' => '18','name' => 'GWIWA'),
        array('id' => '342','state_id' => '18','name' => 'HADEJIA'),
        array('id' => '343','state_id' => '18','name' => 'JAHUN'),
        array('id' => '344','state_id' => '18','name' => 'KAFIN HAUSA'),
        array('id' => '345','state_id' => '18','name' => 'KAZAURE'),
        array('id' => '346','state_id' => '18','name' => 'KIRI KASAMA'),
        array('id' => '347','state_id' => '18','name' => 'KIYAWA'),
        array('id' => '348','state_id' => '18','name' => 'KAUGAMA'),
        array('id' => '349','state_id' => '18','name' => 'MAIGATARI'),
        array('id' => '350','state_id' => '18','name' => 'MALAM MADORI'),
        array('id' => '351','state_id' => '18','name' => 'MIGA'),
        array('id' => '352','state_id' => '18','name' => 'RINGIM'),
        array('id' => '353','state_id' => '18','name' => 'RONI'),
        array('id' => '354','state_id' => '18','name' => 'SULE TANKARKAR'),
        array('id' => '355','state_id' => '18','name' => 'TAURA'),
        array('id' => '356','state_id' => '18','name' => 'YANKWASHI'),
        array('id' => '357','state_id' => '19','name' => 'BIRNIN GWARI'),
        array('id' => '358','state_id' => '19','name' => 'CHIKUN'),
        array('id' => '359','state_id' => '19','name' => 'GIWA'),
        array('id' => '360','state_id' => '19','name' => 'IGABI'),
        array('id' => '361','state_id' => '19','name' => 'IKARA'),
        array('id' => '362','state_id' => '19','name' => 'JABA'),
        array('id' => '363','state_id' => '19','name' => 'JEMA\'A'),
        array('id' => '364','state_id' => '19','name' => 'KACHIA'),
        array('id' => '365','state_id' => '19','name' => 'KADUNA NORTH'),
        array('id' => '366','state_id' => '19','name' => 'KADUNA SOUTH'),
        array('id' => '367','state_id' => '19','name' => 'KAGARKO'),
        array('id' => '368','state_id' => '19','name' => 'KAJURU'),
        array('id' => '369','state_id' => '19','name' => 'KAURA'),
        array('id' => '370','state_id' => '19','name' => 'KAURU'),
        array('id' => '371','state_id' => '19','name' => 'KUBAU'),
        array('id' => '372','state_id' => '19','name' => 'KUDAN'),
        array('id' => '373','state_id' => '19','name' => 'LERE'),
        array('id' => '374','state_id' => '19','name' => 'MAKARFI'),
        array('id' => '375','state_id' => '19','name' => 'SABON GARI'),
        array('id' => '376','state_id' => '19','name' => 'SANGA'),
        array('id' => '377','state_id' => '19','name' => 'SOBA'),
        array('id' => '378','state_id' => '19','name' => 'ZANGON KATAF'),
        array('id' => '379','state_id' => '19','name' => 'ZARIA'),
        array('id' => '380','state_id' => '20','name' => 'AJINGI'),
        array('id' => '381','state_id' => '20','name' => 'ALBASU'),
        array('id' => '382','state_id' => '20','name' => 'BAGWAI'),
        array('id' => '383','state_id' => '20','name' => 'BEBEJI'),
        array('id' => '384','state_id' => '20','name' => 'BICHI'),
        array('id' => '385','state_id' => '20','name' => 'BUNKURE'),
        array('id' => '386','state_id' => '20','name' => 'DALA'),
        array('id' => '387','state_id' => '20','name' => 'DAMBATTA'),
        array('id' => '388','state_id' => '20','name' => 'DAWAKIN KUDU'),
        array('id' => '389','state_id' => '20','name' => 'DAWAKIN TOFA'),
        array('id' => '390','state_id' => '20','name' => 'DOGUWA'),
        array('id' => '391','state_id' => '20','name' => 'FAGGE'),
        array('id' => '392','state_id' => '20','name' => 'GABASAWA'),
        array('id' => '393','state_id' => '20','name' => 'GARKO'),
        array('id' => '394','state_id' => '20','name' => 'GARUN MALLAM'),
        array('id' => '395','state_id' => '20','name' => 'GAYA'),
        array('id' => '396','state_id' => '20','name' => 'GEZAWA'),
        array('id' => '397','state_id' => '20','name' => 'GWALE'),
        array('id' => '398','state_id' => '20','name' => 'GWARZO'),
        array('id' => '399','state_id' => '20','name' => 'KABO'),
        array('id' => '400','state_id' => '20','name' => 'KANO MUNICIPAL'),
        array('id' => '401','state_id' => '20','name' => 'KARAYE'),
        array('id' => '402','state_id' => '20','name' => 'KIBIYA'),
        array('id' => '403','state_id' => '20','name' => 'KIRU'),
        array('id' => '404','state_id' => '20','name' => 'KUMBOTSO'),
        array('id' => '405','state_id' => '20','name' => 'KUNCHI'),
        array('id' => '406','state_id' => '20','name' => 'KURA'),
        array('id' => '407','state_id' => '20','name' => 'MADOBI'),
        array('id' => '408','state_id' => '20','name' => 'MAKODA'),
        array('id' => '409','state_id' => '20','name' => 'MINJIBIR'),
        array('id' => '410','state_id' => '20','name' => 'NASARAWA'),
        array('id' => '411','state_id' => '20','name' => 'RANO'),
        array('id' => '412','state_id' => '20','name' => 'RIMIN GADO'),
        array('id' => '413','state_id' => '20','name' => 'ROGO'),
        array('id' => '414','state_id' => '20','name' => 'SHANONO'),
        array('id' => '415','state_id' => '20','name' => 'SUMAILA'),
        array('id' => '416','state_id' => '20','name' => 'TAKAI'),
        array('id' => '417','state_id' => '20','name' => 'TARAUNI'),
        array('id' => '418','state_id' => '20','name' => 'TOFA'),
        array('id' => '419','state_id' => '20','name' => 'TSANYAWA'),
        array('id' => '420','state_id' => '20','name' => 'TUDUN WADA'),
        array('id' => '421','state_id' => '20','name' => 'UNGOGO'),
        array('id' => '422','state_id' => '20','name' => 'WARAWA'),
        array('id' => '423','state_id' => '20','name' => 'WUDIL'),
        array('id' => '424','state_id' => '21','name' => 'BAKORI'),
        array('id' => '425','state_id' => '21','name' => 'BATAGARAWA'),
        array('id' => '426','state_id' => '21','name' => 'BATSARI'),
        array('id' => '427','state_id' => '21','name' => 'BAURE'),
        array('id' => '428','state_id' => '21','name' => 'BINDAWA'),
        array('id' => '429','state_id' => '21','name' => 'CHARANCHI'),
        array('id' => '430','state_id' => '21','name' => 'DANDUME'),
        array('id' => '431','state_id' => '21','name' => 'DANJA'),
        array('id' => '432','state_id' => '21','name' => 'DAN MUSA'),
        array('id' => '433','state_id' => '21','name' => 'DAURA'),
        array('id' => '434','state_id' => '21','name' => 'DUTSI'),
        array('id' => '435','state_id' => '21','name' => 'DUTSIN MA'),
        array('id' => '436','state_id' => '21','name' => 'FASKARI'),
        array('id' => '437','state_id' => '21','name' => 'FUNTUA'),
        array('id' => '438','state_id' => '21','name' => 'INGAWA'),
        array('id' => '439','state_id' => '21','name' => 'JIBIA'),
        array('id' => '440','state_id' => '21','name' => 'KAFUR'),
        array('id' => '441','state_id' => '21','name' => 'KAITA'),
        array('id' => '442','state_id' => '21','name' => 'KANKARA'),
        array('id' => '443','state_id' => '21','name' => 'KANKIA'),
        array('id' => '444','state_id' => '21','name' => 'KATSINA'),
        array('id' => '445','state_id' => '21','name' => 'KURFI'),
        array('id' => '446','state_id' => '21','name' => 'KUSADA'),
        array('id' => '447','state_id' => '21','name' => 'MAI\'ADUA'),
        array('id' => '448','state_id' => '21','name' => 'MALUMFASHI'),
        array('id' => '449','state_id' => '21','name' => 'MANI'),
        array('id' => '450','state_id' => '21','name' => 'MASHI'),
        array('id' => '451','state_id' => '21','name' => 'MATAZU'),
        array('id' => '452','state_id' => '21','name' => 'MUSAWA'),
        array('id' => '453','state_id' => '21','name' => 'RIMI'),
        array('id' => '454','state_id' => '21','name' => 'SABUWA'),
        array('id' => '455','state_id' => '21','name' => 'SAFANA'),
        array('id' => '456','state_id' => '21','name' => 'SANDAMU'),
        array('id' => '457','state_id' => '21','name' => 'ZANGO'),
        array('id' => '458','state_id' => '22','name' => 'ALEIRO'),
        array('id' => '459','state_id' => '22','name' => 'AREWA DANDI'),
        array('id' => '460','state_id' => '22','name' => 'ARGUNGU'),
        array('id' => '461','state_id' => '22','name' => 'AUGIE'),
        array('id' => '462','state_id' => '22','name' => 'BAGUDO'),
        array('id' => '463','state_id' => '22','name' => 'BIRNIN KEBBI'),
        array('id' => '464','state_id' => '22','name' => 'BUNZA'),
        array('id' => '465','state_id' => '22','name' => 'DANDI'),
        array('id' => '466','state_id' => '22','name' => 'FAKAI'),
        array('id' => '467','state_id' => '22','name' => 'GWANDU'),
        array('id' => '468','state_id' => '22','name' => 'JEGA'),
        array('id' => '469','state_id' => '22','name' => 'KALGO'),
        array('id' => '470','state_id' => '22','name' => 'KOKO/BESSE'),
        array('id' => '471','state_id' => '22','name' => 'MAIYAMA'),
        array('id' => '472','state_id' => '22','name' => 'NGASKI'),
        array('id' => '473','state_id' => '22','name' => 'SAKABA'),
        array('id' => '474','state_id' => '22','name' => 'SHANGA'),
        array('id' => '475','state_id' => '22','name' => 'SURU'),
        array('id' => '476','state_id' => '22','name' => 'WASAGU/DANKO'),
        array('id' => '477','state_id' => '22','name' => 'YAURI'),
        array('id' => '478','state_id' => '22','name' => 'ZURU'),
        array('id' => '479','state_id' => '23','name' => 'ADAVI'),
        array('id' => '480','state_id' => '23','name' => 'AJAOKUTA'),
        array('id' => '481','state_id' => '23','name' => 'ANKPA'),
        array('id' => '482','state_id' => '23','name' => 'BASSA'),
        array('id' => '483','state_id' => '23','name' => 'DEKINA'),
        array('id' => '484','state_id' => '23','name' => 'IBAJI'),
        array('id' => '485','state_id' => '23','name' => 'IDAH'),
        array('id' => '486','state_id' => '23','name' => 'IGALAMELA ODOLU'),
        array('id' => '487','state_id' => '23','name' => 'IJUMU'),
        array('id' => '488','state_id' => '23','name' => 'KABBA/BUNU'),
        array('id' => '489','state_id' => '23','name' => 'KOGI'),
        array('id' => '490','state_id' => '23','name' => 'LOKOJA'),
        array('id' => '491','state_id' => '23','name' => 'MOPA MURO'),
        array('id' => '492','state_id' => '23','name' => 'OFU'),
        array('id' => '493','state_id' => '23','name' => 'OGORI/MAGONGO'),
        array('id' => '494','state_id' => '23','name' => 'OKEHI'),
        array('id' => '495','state_id' => '23','name' => 'OKENE'),
        array('id' => '496','state_id' => '23','name' => 'OLAMABORO'),
        array('id' => '497','state_id' => '23','name' => 'OMALA'),
        array('id' => '498','state_id' => '23','name' => 'YAGBA EAST'),
        array('id' => '499','state_id' => '23','name' => 'YAGBA WEST'),
        array('id' => '500','state_id' => '24','name' => 'ASA'),
        array('id' => '501','state_id' => '24','name' => 'BARUTEN'),
        array('id' => '502','state_id' => '24','name' => 'EDU'),
        array('id' => '503','state_id' => '24','name' => 'EKITI'),
        array('id' => '504','state_id' => '24','name' => 'IFELODUN'),
        array('id' => '505','state_id' => '24','name' => 'ILORIN EAST'),
        array('id' => '506','state_id' => '24','name' => 'ILORIN SOUTH'),
        array('id' => '507','state_id' => '24','name' => 'ILORIN WEST'),
        array('id' => '508','state_id' => '24','name' => 'IREPODUN'),
        array('id' => '509','state_id' => '24','name' => 'ISIN'),
        array('id' => '510','state_id' => '24','name' => 'KAIAMA'),
        array('id' => '511','state_id' => '24','name' => 'MORO'),
        array('id' => '512','state_id' => '24','name' => 'OFFA'),
        array('id' => '513','state_id' => '24','name' => 'OKE ERO'),
        array('id' => '514','state_id' => '24','name' => 'OYUN'),
        array('id' => '515','state_id' => '24','name' => 'PATEGI'),
        array('id' => '516','state_id' => '25','name' => 'AGEGE'),
        array('id' => '517','state_id' => '25','name' => 'AJEROMI-IFELODUN'),
        array('id' => '518','state_id' => '25','name' => 'ALIMOSHO'),
        array('id' => '519','state_id' => '25','name' => 'AMUWO-ODOFIN'),
        array('id' => '520','state_id' => '25','name' => 'APAPA'),
        array('id' => '521','state_id' => '25','name' => 'BADAGRY'),
        array('id' => '522','state_id' => '25','name' => 'EPE'),
        array('id' => '523','state_id' => '25','name' => 'ETI OSA'),
        array('id' => '524','state_id' => '25','name' => 'IBEJU-LEKKI'),
        array('id' => '525','state_id' => '25','name' => 'IFAKO-IJAIYE'),
        array('id' => '526','state_id' => '25','name' => 'IKEJA'),
        array('id' => '527','state_id' => '25','name' => 'IKORODU'),
        array('id' => '528','state_id' => '25','name' => 'KOSOFE'),
        array('id' => '529','state_id' => '25','name' => 'LAGOS ISLAND'),
        array('id' => '530','state_id' => '25','name' => 'LAGOS MAINLAND'),
        array('id' => '531','state_id' => '25','name' => 'MUSHIN'),
        array('id' => '532','state_id' => '25','name' => 'OJO'),
        array('id' => '533','state_id' => '25','name' => 'OSHODI-ISOLO'),
        array('id' => '534','state_id' => '25','name' => 'SHOMOLU'),
        array('id' => '535','state_id' => '25','name' => 'SURULERE'),
        array('id' => '536','state_id' => '26','name' => 'AKWANGA'),
        array('id' => '537','state_id' => '26','name' => 'AWE'),
        array('id' => '538','state_id' => '26','name' => 'DOMA'),
        array('id' => '539','state_id' => '26','name' => 'KARU'),
        array('id' => '540','state_id' => '26','name' => 'KEANA'),
        array('id' => '541','state_id' => '26','name' => 'KEFFI'),
        array('id' => '542','state_id' => '26','name' => 'KOKONA'),
        array('id' => '543','state_id' => '26','name' => 'LAFIA'),
        array('id' => '544','state_id' => '26','name' => 'NASARAWA'),
        array('id' => '545','state_id' => '26','name' => 'NASARAWA EGON'),
        array('id' => '546','state_id' => '26','name' => 'OBI'),
        array('id' => '547','state_id' => '26','name' => 'TOTO'),
        array('id' => '548','state_id' => '26','name' => 'WAMBA'),
        array('id' => '549','state_id' => '26','name' => 'OBI'),
        array('id' => '550','state_id' => '27','name' => 'AGAIE'),
        array('id' => '551','state_id' => '27','name' => 'AGWARA'),
        array('id' => '552','state_id' => '27','name' => 'BIDA'),
        array('id' => '553','state_id' => '27','name' => 'BORGU'),
        array('id' => '554','state_id' => '27','name' => 'BOSSO'),
        array('id' => '555','state_id' => '27','name' => 'CHANCHAGA'),
        array('id' => '556','state_id' => '27','name' => 'EDATI'),
        array('id' => '557','state_id' => '27','name' => 'GBAKO'),
        array('id' => '558','state_id' => '27','name' => 'GURARA'),
        array('id' => '559','state_id' => '27','name' => 'KATCHA'),
        array('id' => '560','state_id' => '27','name' => 'KONTAGORA'),
        array('id' => '561','state_id' => '27','name' => 'LAPAI'),
        array('id' => '562','state_id' => '27','name' => 'LAVUN'),
        array('id' => '563','state_id' => '27','name' => 'MAGAMA'),
        array('id' => '564','state_id' => '27','name' => 'MARIGA'),
        array('id' => '565','state_id' => '27','name' => 'MASHEGU'),
        array('id' => '566','state_id' => '27','name' => 'MOKWA'),
        array('id' => '567','state_id' => '27','name' => 'MOYA'),
        array('id' => '568','state_id' => '27','name' => 'PAIKORO'),
        array('id' => '569','state_id' => '27','name' => 'RAFI'),
        array('id' => '570','state_id' => '27','name' => 'RIJAU'),
        array('id' => '571','state_id' => '27','name' => 'SHIRORO'),
        array('id' => '572','state_id' => '27','name' => 'SULEJA'),
        array('id' => '573','state_id' => '27','name' => 'TAFA'),
        array('id' => '574','state_id' => '27','name' => 'WUSHISHI'),
        array('id' => '575','state_id' => '28','name' => 'ABEOKUTA NORTH'),
        array('id' => '576','state_id' => '28','name' => 'ABEOKUTA SOUTH'),
        array('id' => '577','state_id' => '28','name' => 'ADO-ODO/OTA'),
        array('id' => '578','state_id' => '28','name' => 'YEWA NORTH'),
        array('id' => '579','state_id' => '28','name' => 'YEWA SOUTH'),
        array('id' => '580','state_id' => '28','name' => 'EWEKORO'),
        array('id' => '581','state_id' => '28','name' => 'IFO'),
        array('id' => '582','state_id' => '28','name' => 'IJEBU EAST'),
        array('id' => '583','state_id' => '28','name' => 'IJEBU NORTH'),
        array('id' => '584','state_id' => '28','name' => 'IJEBU NORTH EAST'),
        array('id' => '585','state_id' => '28','name' => 'IJEBU ODE'),
        array('id' => '586','state_id' => '28','name' => 'IKENNE'),
        array('id' => '587','state_id' => '28','name' => 'IMEKO AFON'),
        array('id' => '588','state_id' => '28','name' => 'IPOKIA'),
        array('id' => '589','state_id' => '28','name' => 'OBAFEMI OWODE'),
        array('id' => '590','state_id' => '28','name' => 'ODEDA'),
        array('id' => '591','state_id' => '28','name' => 'ODOGBOLU'),
        array('id' => '592','state_id' => '28','name' => 'OGUN WATERSIDE'),
        array('id' => '593','state_id' => '28','name' => 'REMO NORTH'),
        array('id' => '594','state_id' => '28','name' => 'SHAGAMU'),
        array('id' => '595','state_id' => '29','name' => 'AKOKO NORTH-EAST'),
        array('id' => '596','state_id' => '29','name' => 'AKOKO NORTH-WEST'),
        array('id' => '597','state_id' => '29','name' => 'AKOKO SOUTH-WEST'),
        array('id' => '598','state_id' => '29','name' => 'AKOKO SOUTH-EAST'),
        array('id' => '599','state_id' => '29','name' => 'AKURE NORTH'),
        array('id' => '600','state_id' => '29','name' => 'AKURE SOUTH'),
        array('id' => '601','state_id' => '29','name' => 'ESE ODO'),
        array('id' => '602','state_id' => '29','name' => 'IDANRE'),
        array('id' => '603','state_id' => '29','name' => 'IFEDORE'),
        array('id' => '604','state_id' => '29','name' => 'ILAJE'),
        array('id' => '605','state_id' => '29','name' => 'ILE OLUJI/OKEIGBO'),
        array('id' => '606','state_id' => '29','name' => 'IRELE'),
        array('id' => '607','state_id' => '29','name' => 'ODIGBO'),
        array('id' => '608','state_id' => '29','name' => 'OKITIPUPA'),
        array('id' => '609','state_id' => '29','name' => 'ONDO EAST'),
        array('id' => '610','state_id' => '29','name' => 'ONDO WEST'),
        array('id' => '611','state_id' => '29','name' => 'OSE'),
        array('id' => '612','state_id' => '29','name' => 'OWO'),
        array('id' => '613','state_id' => '30','name' => 'ATAKUNMOSA EAST'),
        array('id' => '614','state_id' => '30','name' => 'ATAKUNMOSA WEST'),
        array('id' => '615','state_id' => '30','name' => 'AIYEDAADE'),
        array('id' => '616','state_id' => '30','name' => 'AIYEDIRE'),
        array('id' => '617','state_id' => '30','name' => 'BOLUWADURO'),
        array('id' => '618','state_id' => '30','name' => 'BORIPE'),
        array('id' => '619','state_id' => '30','name' => 'EDE NORTH'),
        array('id' => '620','state_id' => '30','name' => 'EDE SOUTH'),
        array('id' => '621','state_id' => '30','name' => 'IFE CENTRAL'),
        array('id' => '622','state_id' => '30','name' => 'IFE EAST'),
        array('id' => '623','state_id' => '30','name' => 'IFE NORTH'),
        array('id' => '624','state_id' => '30','name' => 'IFE SOUTH'),
        array('id' => '625','state_id' => '30','name' => 'EGBEDORE'),
        array('id' => '626','state_id' => '30','name' => 'EJIGBO'),
        array('id' => '627','state_id' => '30','name' => 'IFEDAYO'),
        array('id' => '628','state_id' => '30','name' => 'IFELODUN'),
        array('id' => '629','state_id' => '30','name' => 'ILA'),
        array('id' => '630','state_id' => '30','name' => 'ILESA EAST'),
        array('id' => '631','state_id' => '30','name' => 'ILESA WEST'),
        array('id' => '632','state_id' => '30','name' => 'IREPODUN'),
        array('id' => '633','state_id' => '30','name' => 'IREWOLE'),
        array('id' => '634','state_id' => '30','name' => 'ISOKAN'),
        array('id' => '635','state_id' => '30','name' => 'IWO'),
        array('id' => '636','state_id' => '30','name' => 'OBOKUN'),
        array('id' => '637','state_id' => '30','name' => 'ODO OTIN'),
        array('id' => '638','state_id' => '30','name' => 'OLA OLUWA'),
        array('id' => '639','state_id' => '30','name' => 'OLORUNDA'),
        array('id' => '640','state_id' => '30','name' => 'ORIADE'),
        array('id' => '641','state_id' => '30','name' => 'OROLU'),
        array('id' => '642','state_id' => '30','name' => 'OSOGBO'),
        array('id' => '643','state_id' => '30','name' => 'OBOKUN'),
        array('id' => '644','state_id' => '31','name' => 'AFIJIO'),
        array('id' => '645','state_id' => '31','name' => 'AKINYELE'),
        array('id' => '646','state_id' => '31','name' => 'ATIBA'),
        array('id' => '647','state_id' => '31','name' => 'ATISBO'),
        array('id' => '648','state_id' => '31','name' => 'EGBEDA'),
        array('id' => '649','state_id' => '31','name' => 'IBADAN NORTH'),
        array('id' => '650','state_id' => '31','name' => 'IBADAN NORTH-EAST'),
        array('id' => '651','state_id' => '31','name' => 'IBADAN NORTH-WEST'),
        array('id' => '652','state_id' => '31','name' => 'IBADAN SOUTH-EAST'),
        array('id' => '653','state_id' => '31','name' => 'IBADAN SOUTH-WEST'),
        array('id' => '654','state_id' => '31','name' => 'IBARAPA CENTRAL'),
        array('id' => '655','state_id' => '31','name' => 'IBARAPA EAST'),
        array('id' => '656','state_id' => '31','name' => 'IBARAPA NORTH'),
        array('id' => '657','state_id' => '31','name' => 'IDO'),
        array('id' => '658','state_id' => '31','name' => 'IREPO'),
        array('id' => '659','state_id' => '31','name' => 'ISEYIN'),
        array('id' => '660','state_id' => '31','name' => 'ITESIWAJU'),
        array('id' => '661','state_id' => '31','name' => 'IWAJOWA'),
        array('id' => '662','state_id' => '31','name' => 'KAJOLA'),
        array('id' => '663','state_id' => '31','name' => 'LAGELU'),
        array('id' => '664','state_id' => '31','name' => 'OGBOMOSHO NORTH'),
        array('id' => '665','state_id' => '31','name' => 'OGBOMOSHO SOUTH'),
        array('id' => '666','state_id' => '31','name' => 'OGO OLUWA'),
        array('id' => '667','state_id' => '31','name' => 'OLORUNSOGO'),
        array('id' => '668','state_id' => '31','name' => 'OLUYOLE'),
        array('id' => '669','state_id' => '31','name' => 'ONA ARA'),
        array('id' => '670','state_id' => '31','name' => 'ORELOPE'),
        array('id' => '671','state_id' => '31','name' => 'ORI IRE'),
        array('id' => '672','state_id' => '31','name' => 'OYO WEST'),
        array('id' => '673','state_id' => '31','name' => 'OYO EAST'),
        array('id' => '674','state_id' => '31','name' => 'SAKI EAST'),
        array('id' => '675','state_id' => '31','name' => 'SAKI WEST'),
        array('id' => '676','state_id' => '31','name' => 'SURULERE'),
        array('id' => '677','state_id' => '32','name' => 'BOKKOS'),
        array('id' => '678','state_id' => '32','name' => 'BARKIN LADI'),
        array('id' => '679','state_id' => '32','name' => 'BASSA'),
        array('id' => '680','state_id' => '32','name' => 'JOS EAST'),
        array('id' => '681','state_id' => '32','name' => 'JOS NORTH'),
        array('id' => '682','state_id' => '32','name' => 'JOS SOUTH'),
        array('id' => '683','state_id' => '32','name' => 'KANAM'),
        array('id' => '684','state_id' => '32','name' => 'KANKE'),
        array('id' => '685','state_id' => '32','name' => 'LANGTANG SOUTH'),
        array('id' => '686','state_id' => '32','name' => 'LANGTANG NORTH'),
        array('id' => '687','state_id' => '32','name' => 'MANGU'),
        array('id' => '688','state_id' => '32','name' => 'MIKANG'),
        array('id' => '689','state_id' => '32','name' => 'PANKSHIN'),
        array('id' => '690','state_id' => '32','name' => 'QUA\'AN PAN'),
        array('id' => '691','state_id' => '32','name' => 'RIYOM'),
        array('id' => '692','state_id' => '32','name' => 'SHENDAM'),
        array('id' => '693','state_id' => '32','name' => 'WASE'),
        array('id' => '694','state_id' => '33','name' => 'ABUA/ODUAL'),
        array('id' => '695','state_id' => '33','name' => 'AHOADA EAST'),
        array('id' => '696','state_id' => '33','name' => 'AHOADA WEST'),
        array('id' => '697','state_id' => '33','name' => 'AKUKU-TORU'),
        array('id' => '698','state_id' => '33','name' => 'ANDONI'),
        array('id' => '699','state_id' => '33','name' => 'ASARI-TORU'),
        array('id' => '700','state_id' => '33','name' => 'BONNY'),
        array('id' => '701','state_id' => '33','name' => 'DEGEMA'),
        array('id' => '702','state_id' => '33','name' => 'ELEME'),
        array('id' => '703','state_id' => '33','name' => 'EMUOHA'),
        array('id' => '704','state_id' => '33','name' => 'ETCHE'),
        array('id' => '705','state_id' => '33','name' => 'GOKANA'),
        array('id' => '706','state_id' => '33','name' => 'IKWERRE'),
        array('id' => '707','state_id' => '33','name' => 'KHANA'),
        array('id' => '708','state_id' => '33','name' => 'OBIO/AKPOR'),
        array('id' => '709','state_id' => '33','name' => 'OGBA/EGBEMA/NDONI'),
        array('id' => '710','state_id' => '33','name' => 'OGU/BOLO'),
        array('id' => '711','state_id' => '33','name' => 'OKRIKA'),
        array('id' => '712','state_id' => '33','name' => 'OMUMA'),
        array('id' => '713','state_id' => '33','name' => 'OPOBO/NKORO'),
        array('id' => '714','state_id' => '33','name' => 'OYIGBO'),
        array('id' => '715','state_id' => '33','name' => 'PORT HARCOURT'),
        array('id' => '716','state_id' => '33','name' => 'TAI'),
        array('id' => '717','state_id' => '33','name' => 'OBIO/AKPOR'),
        array('id' => '718','state_id' => '34','name' => 'BINJI'),
        array('id' => '719','state_id' => '34','name' => 'BODINGA'),
        array('id' => '720','state_id' => '34','name' => 'DANGE SHUNI'),
        array('id' => '721','state_id' => '34','name' => 'GADA'),
        array('id' => '722','state_id' => '34','name' => 'GORONYO'),
        array('id' => '723','state_id' => '34','name' => 'GUDU'),
        array('id' => '724','state_id' => '34','name' => 'GWADABAWA'),
        array('id' => '725','state_id' => '34','name' => 'ILLELA'),
        array('id' => '726','state_id' => '34','name' => 'ISA'),
        array('id' => '727','state_id' => '34','name' => 'KEBBE'),
        array('id' => '728','state_id' => '34','name' => 'KWARE'),
        array('id' => '729','state_id' => '34','name' => 'RABAH'),
        array('id' => '730','state_id' => '34','name' => 'SABON BIRNI'),
        array('id' => '731','state_id' => '34','name' => 'SHAGARI'),
        array('id' => '732','state_id' => '34','name' => 'SILAME'),
        array('id' => '733','state_id' => '34','name' => 'SOKOTO NORTH'),
        array('id' => '734','state_id' => '34','name' => 'SOKOTO SOUTH'),
        array('id' => '735','state_id' => '34','name' => 'TAMBUWAL'),
        array('id' => '736','state_id' => '34','name' => 'TANGAZA'),
        array('id' => '737','state_id' => '34','name' => 'TURETA'),
        array('id' => '738','state_id' => '34','name' => 'WAMAKO'),
        array('id' => '739','state_id' => '34','name' => 'WURNO'),
        array('id' => '740','state_id' => '34','name' => 'YABO'),
        array('id' => '741','state_id' => '35','name' => 'ARDO KOLA'),
        array('id' => '742','state_id' => '35','name' => 'BALI'),
        array('id' => '743','state_id' => '35','name' => 'DONGA'),
        array('id' => '744','state_id' => '35','name' => 'GASHAKA'),
        array('id' => '745','state_id' => '35','name' => 'GASSOL'),
        array('id' => '746','state_id' => '35','name' => 'IBI'),
        array('id' => '747','state_id' => '35','name' => 'JALINGO'),
        array('id' => '748','state_id' => '35','name' => 'KARIM LAMIDO'),
        array('id' => '749','state_id' => '35','name' => 'KUMI'),
        array('id' => '750','state_id' => '35','name' => 'LAU'),
        array('id' => '751','state_id' => '35','name' => 'SARDAUNA'),
        array('id' => '752','state_id' => '35','name' => 'TAKUM'),
        array('id' => '753','state_id' => '35','name' => 'USSA'),
        array('id' => '754','state_id' => '35','name' => 'WUKARI'),
        array('id' => '755','state_id' => '35','name' => 'YORRO'),
        array('id' => '756','state_id' => '35','name' => 'ZING'),
        array('id' => '757','state_id' => '36','name' => 'BADE'),
        array('id' => '758','state_id' => '36','name' => 'BURSARI'),
        array('id' => '759','state_id' => '36','name' => 'DAMATURU'),
        array('id' => '760','state_id' => '36','name' => 'FIKA'),
        array('id' => '761','state_id' => '36','name' => 'FUNE'),
        array('id' => '762','state_id' => '36','name' => 'GEIDAM'),
        array('id' => '763','state_id' => '36','name' => 'GUJBA'),
        array('id' => '764','state_id' => '36','name' => 'GULANI'),
        array('id' => '765','state_id' => '36','name' => 'JAKUSKO'),
        array('id' => '766','state_id' => '36','name' => 'KARASUWA'),
        array('id' => '767','state_id' => '36','name' => 'MACHINA'),
        array('id' => '768','state_id' => '36','name' => 'NANGERE'),
        array('id' => '769','state_id' => '36','name' => 'NGURU'),
        array('id' => '770','state_id' => '36','name' => 'POTISKUM'),
        array('id' => '771','state_id' => '36','name' => 'TARMUWA'),
        array('id' => '772','state_id' => '36','name' => 'YUNUSARI'),
        array('id' => '773','state_id' => '36','name' => 'YUSUFARI'),
        array('id' => '774','state_id' => '37','name' => 'ANKA'),
        array('id' => '775','state_id' => '37','name' => 'BAKURA'),
        array('id' => '776','state_id' => '37','name' => 'BIRNIN MAGAJI/KIYAW'),
        array('id' => '777','state_id' => '37','name' => 'BUKKUYUM'),
        array('id' => '778','state_id' => '37','name' => 'BUNGUDU'),
        array('id' => '779','state_id' => '37','name' => 'GUMMI'),
        array('id' => '780','state_id' => '37','name' => 'GUSAU'),
        array('id' => '781','state_id' => '37','name' => 'KAURA NAMODA'),
        array('id' => '782','state_id' => '37','name' => 'MARADUN'),
        array('id' => '783','state_id' => '37','name' => 'MARU'),
        array('id' => '784','state_id' => '37','name' => 'SHINKAFI'),
        array('id' => '785','state_id' => '37','name' => 'TALATA MAFARA'),
        array('id' => '786','state_id' => '37','name' => 'CHAFE'),
        array('id' => '787','state_id' => '37','name' => 'ZURMI')
        );

        Lga::insert($lgas);
    }
}
